# Workflow to automatically create deliverables
name: Build on push

on:
  [push, pull_request]

jobs:
  build:
    name: Assembling artifacts
    runs-on: ubuntu-20.04

    # Note, to satisfy the asset library we need to make sure our zip files have a root folder
    # this is why we checkout into aar
    # and build into asset
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: aar
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Create Godot OpenXR loader AARs
        run: |
          cd aar
          ./gradlew build
          cd ..
      - name: Create Godot OpenXR loader Asset
        run: |
          mkdir asset
          mkdir asset/android
          mkdir asset/android/plugins
          mkdir asset/android/plugins/godotopenxrmeta
          mkdir asset/android/plugins/godotopenxrpico
          mkdir asset/android/plugins/godotopenxrkhr
          cp aar/CHANGES.md asset/android/plugins/GodotOpenXRLoaders_CHANGES.md
          cp aar/GodotOpenXRMeta.gdap asset/android/plugins/
          cp aar/godotopenxrmeta/LICENSE.txt asset/android/plugins/godotopenxrmeta/
          cp aar/godotopenxrmeta/build/outputs/aar/godotopenxrmeta-debug.aar asset/android/plugins/godotopenxrmeta/
          cp aar/godotopenxrmeta/build/outputs/aar/godotopenxrmeta-release.aar asset/android/plugins/godotopenxrmeta/
          cp aar/GodotOpenXRPico.gdap asset/android/plugins/
          cp aar/godotopenxrpico/src/main/jniLibs/arm64-v8a/README.md asset/android/plugins/godotopenxrpico/LICENSE.md
          cp aar/godotopenxrpico/build/outputs/aar/godotopenxrpico-release.aar asset/android/plugins/godotopenxrpico/
          cp aar/GodotOpenXRKHR.gdap asset/android/plugins/
          cp aar/godotopenxrkhr/LICENSE.md asset/android/plugins/godotopenxrkhr/LICENSE.md
          cp aar/godotopenxrkhr/build/outputs/aar/godotopenxrkhr-release.aar asset/android/plugins/godotopenxrkhr/
      - name: Create Godot OpenXR loader asset artifact
        uses: actions/upload-artifact@v2
        with:
          name: GodotOpenXRLoaders
          path: |
            asset
      - name: Zip asset
        run: |
          zip -qq -r godotopenxrloaders.zip asset
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
      - name: Create and upload asset
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "godotopenxrloaders.zip"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
